### ISSUE TITLE
bug(text-input): wrong primary item text color in dark mode

### ISSUE THREAD

**Issue by acocq** [Decathlon/vitamin-compose#127] opened 2023-03-23 13:35 UTC
**Describe the bug**

On text input dropdown, the primary item text color is black in dark mode. We have to specify a color if we want to be compliant with dark mode.

**Expected behavior**

By default, the text should be using the vtmnContentPrimary color, so "black" text color in light mode, and "white" text color in dark mode 

**Screenshots**

![dropdown_issue](https://user-images.githubusercontent.com/91876382/227219754-5789e7a3-1061-48ab-be24-570a71713b06.png)
<img width="505" alt="Capture d’écran 2023-03-23 à 14 24 30" src="https://user-images.githubusercontent.com/91876382/227219421-8974f0e2-41fb-4a06-ba59-fba5fada5522.png">

**Comment by acocq** [comment] 2023-03-27 07:53
Hello, I agree with you, in the sample app, with almost the same code, there is no visual error.
I am using the `0.3.0-beta1` version of Vitamin

**Comment by FDELAHA24** [comment] 2023-04-07 11:48
Hi @acocq, I still does not reproduce, does this issue happens on specific Android version or devices ?

**Comment by ManonPolle** [comment] 2023-05-02 09:08
Hello, as discussed and as we cannot reproduce in Vitamin Sample, I suggest looking at override styles into your app. I close this issue for now, don't hesitate to re open it if needed.

**Closed by ManonPolle** 2023-05-02 09:08 UTC
Labels: bug 🐛, help wanted ✋
